import { Card, CardStatus } from '@models/collection.models';

export const stubCardList: Card[] = [
  {
    id: 'id-001',
    status: CardStatus.Collected,
    rarity: 'R',
    serial_number: 'R-001',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
  {
    id: 'id-002',
    status: CardStatus.Collected,
    rarity: 'R',
    serial_number: 'R-002',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
  {
    id: 'id-003',
    status: CardStatus.NotExisting,
    rarity: 'R',
    serial_number: 'R-003',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
  {
    id: 'id-004',
    status: CardStatus.NotCollected,
    rarity: 'R',
    serial_number: 'R-004',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
  {
    id: 'id-005',
    status: CardStatus.Collected,
    rarity: 'R',
    serial_number: 'R-005',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
  {
    id: 'id-006',
    status: CardStatus.NotExisting,
    rarity: 'R',
    serial_number: 'R-006',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
  {
    id: 'id-007',
    status: CardStatus.Collected,
    rarity: 'R',
    serial_number: 'R-007',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
  {
    id: 'id-008',
    status: CardStatus.Collected,
    rarity: 'R',
    serial_number: 'R-008',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
  {
    id: 'id-009',
    status: CardStatus.NotCollected,
    rarity: 'R',
    serial_number: 'R-009',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
  {
    id: 'id-010',
    status: CardStatus.NotCollected,
    rarity: 'R',
    serial_number: 'R-010',
    character_name: 'FF',
    image_url: 'assets/img/card-stub.jpg',
  },
];
